server:
  port: 0

spring:
  application:
    name: catalog-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3302/catalog?serverTimezone=UTC&characterEncoding=UTF-8
    username: catalog
    password: 1234
    hikari:
      connection-test-query: SELECT NOW() FROM DUAL
      auto-commit: true
  messages:
    basename: messages
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      format_sql: true
      ddl-auto: update
  security:
    user:
      name: username
      password: passw0rd!
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          dyscription:
            sql:
              BasicBinder: TRACE

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka