INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
VALUES ('Catalog-001', 'Berlin', 100, 1500);
INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
VALUES ('Catalog-002', 'Tokyo', 110, 1000);
INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
VALUES ('Catalog-003', 'Stockholm', 120, 2000);